version: '3.1'

services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - grafana_conf:/etc/grafana
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana

volumes:
  grafana_conf:
  grafana_data:
  grafana_logs: