version: '3.1'

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw  
      MARIADB_USER: example-user 
      MARIADB_PASSWORD: my_cool_secret 
      MARIADB_DATABASE: my_example_db
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:


